### ISSUE TITLE
Some questions about the adjacency matrix

### ISSUE THREAD

**Issue by SakuraiYuuta** [SamsungLabs/eagle#18]
<img width="440" alt="image" src="https://github.com/SamsungLabs/eagle/assets/52504781/f842789d-e327-48f8-a084-ba06e986581a">

nasbench-201 contains networks same as the above figure, same cells connect to form a long network, but I notice that in brp-nas code, adjacency matrix and feature matrix only consider the condition in one cell:
<img width="416" alt="image" src="https://github.com/SamsungLabs/eagle/assets/52504781/40d0dc07-680e-4304-9d30-277ec8cf1e84">

I wonder why only considering one cell's condition can predict latency and accuracy in such a long network, does the latency dataset only measure latency in one cell instead of the whole network?

**Comment by vaenyr** [comment]
The latency dataset contains measurements for the full networks. It is possible to extrapolate a single cell to a full network because the same cell is repeated to form a full. In other words, the transformation used to construct a full model from a single cell is always the same, so the GCN can implicitly learn that.

Having said that, there is probably an opportunity to improve predictions if a full network was used as an input rather than a single cell. However, we couldn't not obtain good results with large graphs passed as input to the GCN back then, so we opted in for conditioning predictions on a single cell instead, which worked ok.

**Comment by SakuraiYuuta** [comment]
It is very reasonable, thank you so much!
